### ISSUE TITLE
Discord hacked 

### ISSUE THREAD

**Issue by iiTranquility** [bebomusa/bgarage#17]
I noticed last night that your Discord was wiped.

Everything okay?

**Comment by BerkieBb** [comment]
He does that from time to time. He changed his discord username like 3 times already

**Comment by iiTranquility** [comment]
> He does that from time to time. He changed his discord username like 3 times already

Everything is gone, no friends, no mutuals, no username change.
![Screenshot_20240223_080003.jpg](https://github.com/bebomusa/bgarage/assets/21291440/71e94978-ddf6-4101-bda7-2401a039403c)

![Screenshot_20240223_075959.jpg](https://github.com/bebomusa/bgarage/assets/21291440/3f1693f4-e9ed-4687-916a-5b958eb3d518)

![Screenshot_20240223_080007.jpg](https://github.com/bebomusa/bgarage/assets/21291440/77f6cd37-2459-42f1-9e04-8bef21744db4)

**Comment by BerkieBb** [comment]
As I said, he just does that from time to time

**Comment by bebomusa** [comment]
@iiTranquility Just specific personal issues have hindered my ability to use that platform. As Berkie mentioned, unusual occurrences like this tend to arise occasionally.
